#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Create and verify a content-free manifest for an online SQLite backup."""

from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
import tempfile
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_REQUIRED_TABLES = ("articles", "chat_history", "users")


def _readonly_connection(path: Path) -> sqlite3.Connection:
    connection = sqlite3.connect(
        f"{path.resolve().as_uri()}?mode=ro",
        uri=True,
        timeout=30,
    )
    connection.execute("PRAGMA query_only=ON")
    return connection


def _quote_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _schema_records(connection: sqlite3.Connection) -> list[dict]:
    rows = connection.execute(
        """
        SELECT type, name, tbl_name, sql
        FROM sqlite_schema
        WHERE name NOT LIKE 'sqlite_%' AND sql IS NOT NULL
        ORDER BY type, name
        """
    ).fetchall()
    return [
        {"type": row[0], "name": row[1], "table": row[2], "sql": row[3]}
        for row in rows
    ]


def _schema_hash(records: list[dict]) -> str:
    payload = json.dumps(
        records,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def inspect_database(
    connection: sqlite3.Connection,
    required_tables: tuple[str, ...] = DEFAULT_REQUIRED_TABLES,
) -> dict:
    integrity_rows = [row[0] for row in connection.execute("PRAGMA integrity_check")]
    schema = _schema_records(connection)
    tables = sorted(
        record["name"] for record in schema if record["type"] == "table"
    )
    indexes = sorted(
        record["name"] for record in schema if record["type"] == "index"
    )
    row_counts = {
        name: int(
            connection.execute(
                f"SELECT COUNT(*) FROM {_quote_identifier(name)}"
            ).fetchone()[0]
        )
        for name in tables
    }
    readonly_queries = {}
    for name in required_tables:
        if name not in tables:
            readonly_queries[name] = "missing"
            continue
        connection.execute(
            f"SELECT 1 FROM {_quote_identifier(name)} LIMIT 1"
        ).fetchone()
        readonly_queries[name] = "passed"
    return {
        "integrity_check": integrity_rows,
        "integrity_ok": integrity_rows == ["ok"],
        "schema_version": int(
            connection.execute("PRAGMA schema_version").fetchone()[0]
        ),
        "user_version": int(
            connection.execute("PRAGMA user_version").fetchone()[0]
        ),
        "schema_sha256": _schema_hash(schema),
        "tables": tables,
        "indexes": indexes,
        "row_counts": row_counts,
        "readonly_queries": readonly_queries,
        "readonly_queries_ok": all(
            result == "passed" for result in readonly_queries.values()
        ),
    }


def _restore_and_inspect(
    backup_path: Path,
    required_tables: tuple[str, ...],
) -> dict:
    with tempfile.TemporaryDirectory(prefix="sqlite-baseline-restore-") as temp_dir:
        restored_path = Path(temp_dir) / "restored.sqlite3"
        source = _readonly_connection(backup_path)
        destination = sqlite3.connect(str(restored_path), timeout=30)
        try:
            source.backup(destination, pages=256, sleep=0.01)
        finally:
            destination.close()
            source.close()
        restored = _readonly_connection(restored_path)
        try:
            result = inspect_database(restored, required_tables)
        finally:
            restored.close()
        result["restored_file_size"] = restored_path.stat().st_size
        result["temporary_restore_removed_after_check"] = True
        return result


def _snapshot_differences(left: dict, right: dict) -> dict:
    fields = (
        "integrity_ok",
        # schema_version is SQLite's mutable internal change counter and may be
        # regenerated by the backup API; schema_sha256 is the semantic check.
        "user_version",
        "schema_sha256",
        "tables",
        "indexes",
        "row_counts",
        "readonly_queries",
        "readonly_queries_ok",
    )
    return {
        field: {"left": left.get(field), "right": right.get(field)}
        for field in fields
        if left.get(field) != right.get(field)
    }


def _snapshot_equal(left: dict, right: dict) -> bool:
    return not _snapshot_differences(left, right)


def create_baseline_backup(
    database_path: str | Path,
    backup_path: str | Path,
    *,
    required_tables: tuple[str, ...] = DEFAULT_REQUIRED_TABLES,
) -> dict:
    source_path = Path(database_path).expanduser().resolve()
    target_path = Path(backup_path).expanduser().resolve()
    if not source_path.is_file() or source_path.stat().st_size == 0:
        raise ValueError(f"source database is missing or empty: {source_path}")
    if target_path.exists():
        raise FileExistsError(f"refusing to overwrite backup: {target_path}")
    if source_path == target_path:
        raise ValueError("source and backup paths must differ")
    target_path.parent.mkdir(parents=True, exist_ok=True)

    source = _readonly_connection(source_path)
    destination = None
    try:
        source.execute("BEGIN")
        source_snapshot = inspect_database(source, required_tables)
        destination = sqlite3.connect(str(target_path), timeout=30)
        source.backup(destination, pages=256, sleep=0.01)
        destination.close()
        destination = None
        source.rollback()
    except Exception:
        if destination is not None:
            destination.close()
        source.close()
        if target_path.exists():
            target_path.unlink()
        raise
    else:
        source.close()

    backup = _readonly_connection(target_path)
    try:
        backup_snapshot = inspect_database(backup, required_tables)
    finally:
        backup.close()
    restored_snapshot = _restore_and_inspect(target_path, required_tables)
    source_backup_differences = _snapshot_differences(
        source_snapshot, backup_snapshot
    )
    backup_restore_differences = _snapshot_differences(
        backup_snapshot, restored_snapshot
    )
    source_matches_backup = not source_backup_differences
    backup_matches_restore = not backup_restore_differences
    accepted = all(
        (
            source_snapshot["integrity_ok"],
            backup_snapshot["integrity_ok"],
            restored_snapshot["integrity_ok"],
            restored_snapshot["readonly_queries_ok"],
            source_matches_backup,
            backup_matches_restore,
        )
    )
    return {
        "manifest_version": "sqlite-online-baseline-v1",
        "captured_at_utc": datetime.now(timezone.utc)
        .isoformat(timespec="seconds")
        .replace("+00:00", "Z"),
        "source_database": str(source_path),
        "backup_database": str(target_path),
        "backup_method": "sqlite3.Connection.backup",
        "backup_file_size": target_path.stat().st_size,
        "backup_sha256": _sha256(target_path),
        "required_readonly_tables": list(required_tables),
        "source_snapshot": source_snapshot,
        "backup_snapshot": backup_snapshot,
        "restore_snapshot": restored_snapshot,
        "acceptance": {
            "source_matches_backup": source_matches_backup,
            "source_backup_differences": source_backup_differences,
            "backup_matches_temporary_restore": backup_matches_restore,
            "backup_restore_differences": backup_restore_differences,
            "integrity_checks_passed": all(
                snapshot["integrity_ok"]
                for snapshot in (
                    source_snapshot,
                    backup_snapshot,
                    restored_snapshot,
                )
            ),
            "readonly_dashboard_history_queries_passed": restored_snapshot[
                "readonly_queries_ok"
            ],
            "passed": accepted,
        },
    }


def verify_backup_manifest(manifest_path: str | Path) -> dict:
    path = Path(manifest_path).expanduser().resolve()
    manifest = json.loads(path.read_text(encoding="utf-8"))
    backup_path = Path(manifest["backup_database"])
    required_tables = tuple(manifest.get("required_readonly_tables") or ())
    differences = {}
    if not backup_path.is_file():
        differences["backup_database"] = "missing"
        return {"manifest": str(path), "valid": False, "differences": differences}
    current_hash = _sha256(backup_path)
    if current_hash != manifest.get("backup_sha256"):
        differences["backup_sha256"] = {
            "saved": manifest.get("backup_sha256"),
            "current": current_hash,
        }
    restored = _restore_and_inspect(backup_path, required_tables)
    if not _snapshot_equal(manifest["backup_snapshot"], restored):
        differences["restore_snapshot"] = "does_not_match_saved_backup_snapshot"
    if not restored["integrity_ok"]:
        differences["integrity_check"] = restored["integrity_check"]
    if not restored["readonly_queries_ok"]:
        differences["readonly_queries"] = restored["readonly_queries"]
    return {
        "manifest": str(path),
        "backup_database": str(backup_path),
        "valid": not differences,
        "differences": differences,
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Online backup and restore-check SQLite")
    parser.add_argument("--database", default="data/crawler_articles.db")
    parser.add_argument(
        "--backup",
        default="backups/baseline/crawler_articles.sqlite3",
    )
    parser.add_argument(
        "--manifest",
        default="baseline/database-backup-manifest.json",
    )
    parser.add_argument("--required-table", action="append", dest="required_tables")
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args(argv)
    if args.verify:
        report = verify_backup_manifest(args.manifest)
        print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
        return 0 if report["valid"] else 2
    required_tables = tuple(args.required_tables or DEFAULT_REQUIRED_TABLES)
    report = create_baseline_backup(
        args.database,
        args.backup,
        required_tables=required_tables,
    )
    manifest_path = Path(args.manifest).expanduser().resolve()
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "manifest": str(manifest_path),
                "backup_database": report["backup_database"],
                "backup_sha256": report["backup_sha256"],
                "table_count": len(report["backup_snapshot"]["tables"]),
                "index_count": len(report["backup_snapshot"]["indexes"]),
                "acceptance": report["acceptance"],
            },
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
    )
    return 0 if report["acceptance"]["passed"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
